### PR TITLE
[WIP] - Add ability for dashboard to send email to relay

### PR DESCRIPTION
**Pull request by jontours**
TLS send code needs to be added.

### CODE REVIEW

**Comment by jontours** [comment]
Added code for initializing cert store.  I remembered while copying this code over from the buildpack PR that I've done this before in Java.  Although in Java it was different, there I'd use command line and add a needed cert to the store that's referenced in the `ca` folder in the JDK for your Java runtime.  I no little of Go, but this seems like we are building the store everytime the code is ran?  Or will the code in `mailer.go` only be ran once?

**Comment by pburkholder** [comment]
Hi @jontours  - have you succeeded in getting a local cg-dashboard dev env set up?

**Comment by jontours** [comment]
I'm working on that currently.

**Comment by timothy-spencer** [comment]
I have no idea why codeclimate is sad, but it looks like you need to add the cert variable to the env_vars.go file too.

**Comment by jontours** [comment]
I did catch that after finally getting this to build on PCF dev.  But now I'm back to not being able to build do to problems with pulling git dependencies.

**Comment by jontours** [comment]
When trying to push this app to `PCF dev` having problems pulling dependencies, usually, but not every time, at this step: 
```
git clone --recursive -v --progress https://github.com/gogo/protobuf /tmp/gobuildpack.gopath118224769/.go/pkg/dep/sources/https---github.com-gogo-protobuf
```

**Comment by jmcarp** [comment]
Looks like this got resubmitted as #1308. Closing.

**Pull request closed without merging**
