### PR TITLE
Setting icon size in the icon component

### PR DESCRIPTION
**Pull request by line47**
Setting up icon size variable and values for small medium and large.

### CODE REVIEW

**Comment by line47** [comment]
Setting this icon size also gets us closer to merging https://github.com/18F/cg-style/pull/225

**Comment by msecret** [comment]
Ahh I didn't want to do this

**Comment by msecret** [comment]
I want to discuss this more and potentially take this commit out:

I designed the icons for a really easy: the conform to the size of the text they're contained in. This is an easier developer interface as the developer doesn't need to know abstract icon size (how big is `small`?) and can just drop icons and have them relatively well sized. Even if the sizes aren't perfect concerning the design, I think this is still a better system and want to push for it.

**Comment by thisisdano** [comment]
I will argue against this

**Comment by msecret** [comment]
Ok, how about we don't make it default to anything. 

This code is actually broken as is, I don't think the correct size class is being passed to the component because it's not passed as an array (which is interesting that the previous method of doing this was so successful that we didn't even realize this wasn't working).

So by default, no size will be defined but the develop can pass a size if necessary.

**Comment by thisisdano** [comment]
That sounds like a good compromise — thanks!

**Pull request merged**
