### PR TITLE
Panel row refactor removal

### PR DESCRIPTION
**Pull request by msecret**
Removes all the deprecated panel code.

Requires https://github.com/18F/cg-style/pull/299

### CODE REVIEW

**Comment by rememberlenny** [comment]
@msecret This looks good. Is there any reason we dont resolve conflicts and merge?

**Comment by msecret** [comment]
Again, this requires 3.0.0 release (sorry not 2.0.0 which I said on other PR) of cg-style.

**Comment by rememberlenny** [comment]
@msecret could you link the cg-style PR? Im not sure what the 3.0.0 release refers to.

**Comment by el-mapache** [comment]
@msecret should we bump `cg-style` up to version 3 then?

**Comment by msecret** [comment]
@el-mapache yea it should be done at some point, IP spring might be best time to do it

**Pull request closed without merging**
