### PR TITLE
Clear `saving` message on error, specs

### PR DESCRIPTION
**Pull request by el-mapache**
**WIP**
* Previously, the `saving` message was sticking around after a user attempted to change a role, but had the action fail. This PR clears that message on failure.

### CODE REVIEW

**Comment by jcscottiii** [comment]
nice! i would just add a functional test to make sure we don't still see it! otherwise LGTM

**Comment by el-mapache** [comment]
@jcscottiii I think a functional test case for this scenario is going to be pretty difficult. We would need to open a second browser window with a different logged in user, toggle the role for the first user, then attempt to have the first user try and remove their own org manager role.

I think it would be pretty straightforward to create a `user_list` spec file and add a test there that verifies that the badge is rendered when that component's `saving` prop is set to true, and doesn't render when it is false.

Let me know if that seems reasonable!

**Comment by jcscottiii** [comment]
@el-mapache yep! that totally makes sense!

**Comment by el-mapache** [comment]
@jcscottiii Added a couple of specs to test for the existence of the 'Saving' badge. Let me know what you think.

**Pull request merged**
