### PR TITLE
Add links for login in email from dashboard

### PR DESCRIPTION
**Pull request by rememberlenny**
screen shot 2017-09-19 at 4 12 01 pm

### CODE REVIEW

**Comment by rememberlenny** [comment]
@jcscottiii Got it. Im adding those in the cg-uaa-extras. Do we want to update this one too?

**Comment by jcscottiii** [comment]
@rememberlenny yeah we need to update them here too with plain text alternatives

**Comment by jcscottiii** [comment]
@rememberlenny also, i think you should take a look at https://cloud-gov.zendesk.com/agent/tickets/688 for more context

**Comment by jcscottiii** [comment]
also, what ever changes you make, you will need to fix the tests. look at the circleci output for more info.

**Comment by jcscottiii** [comment]
@rememberlenny once you're happy with the template, you can run the tests locally and replace the old template with the newly generated `.returned` one.
A snippet from the circle ci run:

```
--- FAIL: TestGetInviteEmail (0.00s)
	templates_test.go:44: Expected invite e-mail template does not match generated invite e-mail template.
	templates_test.go:51: writing expected file to /home/ubuntu/cg-dashboard/helpers/testdata/mail/invite.tmpl.returned
```
just run mv helpers/testdata/mail/invite.tmpl.returned helpers/testdata/mail/invite.tmpl after you run the tests

**Comment by jcscottiii** [comment]
@rememberlenny i reformatted the e-mail

image

**Pull request merged**
