### PR TITLE
Tiny improvement to user guidance

### PR DESCRIPTION
**Pull request by brittag**
Fixing a thing I noticed while trying to use the Dashboard.

### CODE REVIEW

**Comment by msecret** [comment]
Not sure what happened with the failed test on circle, but it doesn't look related to your code change. Will investigate, thanks for the fix!

**Comment by jcscottiii** [comment]
@brittag  @msecret this branch just needs the latest changes from master. it has all the changes pre repo rename :)
image

**Comment by jeremiak** [comment]
I can give it a rebase

**Comment by jeremiak** [comment]
Looks great to me, merging

**Pull request merged**
